import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
// import RecipeCard from "./components/RecipeCard";

export const metadata: Metadata = {
  title: "Recipes App",
  description: "Generated by create next app",
};
// const recipe = {
//   id: 1, // מזהה ייחודי למתכון
//   name: "פסטה עם רוטב עגבניות",
//   category: "איטלקית",
//   image: "path/to/image.jpg",
//   ingredients: ["500 גרם פסטה", "2 שיני שום", "1 בצל"],
//   instructions: [
//     "מבשלים את הפסטה לפי ההוראות על האריזה.",
//     "מטגנים את השום והבצל בשמן זית.",
//   ],
//   isFavorite: false,
// };
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <RecipeCard recipe={recipe}/> */}
      <Header />
      <body>{children}</body>
    </html>
  );
}
